version: '3.6'

services:
  database:
    restart: always
    image: postgres:12
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
    ports:
      - "5444:5432"

  backend:
    links:
      - database
    restart: always
    build: backend/.
    ports:
      - "8090:8090"
    depends_on:
      - database
      - rabbitmq
    volumes:
      - userfiles-data1:/userfiles
      - ./backend/src:/go/src/api

  ocrservice:
    build: ocr/.
    restart: always
    volumes: 
      - userfiles-data1:/userfiles
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  frontend:
    links:
      - backend
    restart: always
    build: frontend/.
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app

volumes:
  database-data:
  userfiles-data1:
