version: '3.6'

services:
  database:
    restart: always
    container_name: project2020_pampaw_database
    image: postgres:12
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
    ports:
      - "5444:5432"

  backend:
    container_name: project2020_pampaw_backend
    links:
      - database
    restart: always
    build: backend/.
    ports:
      - "8090:8090"
    depends_on:
      - database
    volumes:
      - ./backend/src:/go/src/api

volumes:
  database-data:
